#!/usr/bin/env python

import sys

from madrob_settings_gui.madrob_settings_gui import madrob_settings_gui
from rqt_gui.main import Main

main = Main(filename='madrob_settings_gui')
sys.exit(main.main(standalone='madrob_settings_gui'))
