#!/usr/bin/env python

import sys

from beast_settings_gui.beast_settings_gui import beast_settings_gui
from rqt_gui.main import Main

main = Main(filename='beast_settings_gui')
sys.exit(main.main(standalone='beast_settings_gui'))
